name: Golden UML ModelSet Submission
description: With this form, you can submit a case for inclusion in the community-curated Golden UML ModelSet
body:
  - type: markdown
    attributes:
      value: "With this form, you can submit a case for inclusion in the community-curated Golden UML ModelSet. Your case will be reviewed before it is published online. If you have any questions about the reviewing/publishing process, or issues with this form, you can contact charlotte.verbruggen@tuwien.ac.at. Thank you for contributing to the Golden UML ModelSet!"
  - type: input
    id: contact-for-review
    attributes:
      label: Contact info for case reviewing and publishing
      description: Please enter the email address(es) we can use during the reviewing and publishing process of your case.
      placeholder: ex. email@example.com
    validations:
      required: true
 - type: markdown
    attributes:
      value: "Please upload a file called metadata.txt containing the following information"
 - type: textarea
    id: metadata
    attributes:
      label: Metadata
      description: Please upload a file called "metadata.txt" containing the information as described above.
    validations:
      required: true
